version: 2
sources:
  - name: erp
    description: Fonte do SAP de vendas
    schema: erp_northwind
    tables:
      - name: products
      - name: categories
      - name: suppliers
      - name: customers
      - name: orders
        description: Uma linha por pedirdo. inclui pedidos cancelados e deletados.
        columns:
          - name: order_id
            tests:
              - unique
              - not_null
      - name: order_details
      - name: employees
      - name: employee_territories
      - name: territories
      - name: region
      - name: shippers
